/**
 * GENERATED by apx-testgen from pages/p00011-decline-drawer.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00011-decline-drawer.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: form, buttons
 * No interactiveReport/cards/facetedSearch regions on this page -- no region resolve-check to emit.
 * Other region types NOT covered by an auto-generated assertion (no verified DOM convention -- see docs/grammar-assumptions.md "Still open"): form (staticContent), buttons (staticContent).
 * NOT AUTO-ROUTABLE (modalDialog): this page declares appearance.pageMode: modalDialog -- confirmed live that a plain GET returns HTTP 400 instead of loading (docs/quirks/26.1.json 'drawer-modal-pages-400'). Every test below is unconditionally skipped rather than generated to guaranteed-fail.
 * NOT AUTO-ROUTABLE (navigation unsafe): apx-testkit: navigation unsafe (security.pageAccessProtection: argumentsMustHaveChecksum on a non-public page) -- a bare page.goto() is confirmed to redirect an authenticated session to /login. See @apx/testkit's navigateViaUiPath() for the confirmed-working alternative, and docs/quirks/26.1.json page-access-protection-blocks-bare-navigation.
 */
import { expect, test } from '@playwright/test';
import { expectItemsPresent, expectButtonsPresent, normalizeTitle } from '@apx/testkit';
import { DeclineDrawerPage } from './p00011-decline-drawer.page.js';

test.describe('page 11: Decline Invitation [not auto-routable -- skipped]', () => {
  test.beforeEach(async () => {
    // apx-testkit: this page cannot be safely reached by a normal
    // generated test -- see this file's header comment (NOT
    // AUTO-ROUTABLE lines) for the specific reason(s). Every test below
    // is unconditionally skipped rather than generated to
    // guaranteed-fail.
    test.skip(
      true,
      'apx-testkit: modalDialog requires parent-page navigation (a plain GET to this page returns HTTP 400) -- see docs/quirks/26.1.json drawer-modal-pages-400. apx-testkit: navigation unsafe (security.pageAccessProtection: argumentsMustHaveChecksum on a non-public page) -- a bare page.goto() is confirmed to redirect an authenticated session to /login. See @apx/testkit\'s navigateViaUiPath() for the confirmed-working alternative, and docs/quirks/26.1.json page-access-protection-blocks-bare-navigation.',
    );
  });
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new DeclineDrawerPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new DeclineDrawerPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Decline Invitation'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (3 items, 2 hidden)', async ({ page }) => {
    const po = new DeclineDrawerPage(page);
    await po.goto();
    await expectItemsPresent(page, ['P11_ROSTER_ID', 'P11_ROW_VERSION', 'P11_REASON'], 11);
  });

  test('apex.item round-trip on P11_REASON', async ({ page }) => {
    const po = new DeclineDrawerPage(page);
    await po.goto();
    await po.reason.setValue('apx-testgen');
    expect(await po.reason.getValue()).toBe('apx-testgen');
  });

  test('every uniquely labeled .apx button exists (2 buttons)', async ({ page }) => {
    const po = new DeclineDrawerPage(page);
    await po.goto();
    await expectButtonsPresent(page, ['Cancel', 'Confirm Decline'], [{ pageId: 11, identifier: 'cancel' }, { pageId: 11, identifier: 'confirm-decline' }]);
  });
});
