/**
 * GENERATED by apx-testgen from pages/p00010-musician-portal.apx — DO NOT EDIT.
 * Regenerate after any .apx change; review this file's diff alongside the .apx diff.
 * Assertions limited to runtime-verified contracts (V1-V6), implemented once in
 * @apx/testkit — see that package before touching any of the helpers used below.
 * Navigation and item access go through the generated page object
 * (./p00010-musician-portal.page.js), not raw testkit calls, so both stay in sync.
 * Regions present in metadata: breadcrumb, pending-invitations, confirmed-services, my-blockouts
 * Region resolve-check emitted for 3 interactiveReport/cards/facetedSearch region(s) below -- resolved LIVE via resolveRegion() (ADR-003: htmlDomId tried first when set, then the export identifier), never a static id baked in at generation time.
 * Other region types NOT covered by an auto-generated assertion (no verified DOM convention -- see docs/grammar-assumptions.md "Still open"): breadcrumb (breadcrumb).
 * NOT AUTO-ROUTABLE (navigation unsafe): apx-testkit: navigation unsafe (security.pageAccessProtection: argumentsMustHaveChecksum on a non-public page) -- a bare page.goto() is confirmed to redirect an authenticated session to /login. See @apx/testkit's navigateViaUiPath() for the confirmed-working alternative, and docs/quirks/26.1.json page-access-protection-blocks-bare-navigation.
 */
import { expect, test } from '@playwright/test';
import { expectItemsPresent, expectButtonsPresent, resolveRegion, normalizeTitle } from '@apx/testkit';
import { MusicianPortalPage } from './p00010-musician-portal.page.js';

test.describe('page 10: Musician Portal [not auto-routable -- skipped]', () => {
  test.beforeEach(async () => {
    // apx-testkit: this page cannot be safely reached by a normal
    // generated test -- see this file's header comment (NOT
    // AUTO-ROUTABLE lines) for the specific reason(s). Every test below
    // is unconditionally skipped rather than generated to
    // guaranteed-fail.
    test.skip(
      true,
      'apx-testkit: navigation unsafe (security.pageAccessProtection: argumentsMustHaveChecksum on a non-public page) -- a bare page.goto() is confirmed to redirect an authenticated session to /login. See @apx/testkit\'s navigateViaUiPath() for the confirmed-working alternative, and docs/quirks/26.1.json page-access-protection-blocks-bare-navigation.',
    );
  });
  test('loads via alias URL with clean console' , async ({ page }) => {
    const po = new MusicianPortalPage(page);
    const errors = await po.goto();
    await page.waitForTimeout(1000);
    expect(errors).toEqual([]);
  });

  test('title matches metadata (normalized)', async ({ page }) => {
    const po = new MusicianPortalPage(page);
    await po.goto();
    expect(normalizeTitle(await page.title())).toBe(normalizeTitle('Musician Portal'));
  });

  test('every .apx pageItem exists in DOM/apex.item registry (3 items, 3 hidden)', async ({ page }) => {
    const po = new MusicianPortalPage(page);
    await po.goto();
    await expectItemsPresent(page, ['P10_ACTION', 'P10_ROSTER_ID', 'P10_ROW_VERSION'], 10);
  });

  test('every uniquely labeled .apx button exists (1 button)', async ({ page }) => {
    const po = new MusicianPortalPage(page);
    await po.goto();
    await expectButtonsPresent(page, ['Schedule Blockout'], [{ pageId: 10, identifier: 'schedule-blockout' }]);
  });

  test('every interactiveReport/cards/facetedSearch region resolves (3 regions)', async ({ page }) => {
    const po = new MusicianPortalPage(page);
    await po.goto();
    // ADR-003 layered resolution, confirmed LIVE per region (htmlDomId
    // tried first when set, then the export identifier) -- resolveRegion()
    // hard-fails with a specific message if neither candidate resolves,
    // rather than silently trusting a static guess.
    const regionCandidateSets = [
      { identifier: 'pending-invitations', candidates: [{ value: 'pending-invitations', strategy: 'export-identifier' as const }] },
      { identifier: 'confirmed-services', candidates: [{ value: 'confirmed-services', strategy: 'export-identifier' as const }] },
      { identifier: 'my-blockouts', candidates: [{ value: 'my-blockouts', strategy: 'export-identifier' as const }] }
    ];
    for (const { identifier, candidates } of regionCandidateSets) {
      await resolveRegion(page, candidates, { pageId: 10, identifier });
    }
  });
});
