/**
 * GENERATED by apx-testgen from pages/p00012-blockout-modal.apx — DO NOT EDIT.
 * Typed accessor page object built on @apx/testkit primitives — no raw
 * selectors. Item accessors rest on the VERIFIED apex.item contract; button
 * methods use accessible-role/label locators (region/button DOM convention
 * still open — see docs/grammar-assumptions.md). Click methods pass their
 * button's semantic identity (pageId + .apx identifier) through to
 * clickButton() so coverage tracking never collapses two different,
 * same-labeled buttons into one entry -- see @apx/testkit's coverage.ts.
 * Buttons whose label collides with another button's on this same page do
 * NOT get a generated click method at all -- see the comment in their
 * place below for why and what would resolve it.
 */
import type { Page } from '@playwright/test';
import { ApexItem, apexPageUrl, clickButton } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

export class BlockoutModalPage {
  static readonly alias = 'blockout-modal';

  constructor(private readonly page: Page) {}

  url(): string {
    return apexPageUrl(APP_BASE, BlockoutModalPage.alias, true);
  }

  /** Navigate only when the page's declared security/mode permits a direct URL. */
  async goto(): Promise<string[]> {
    throw new Error('This page declares appearance.pageMode: modalDialog and must be opened from a parent page; direct navigation is not supported.');
  }

  /** datePicker, "Start Date" */
  get startDate(): ApexItem {
    return new ApexItem(this.page, 'P12_START_DATE', 12);
  }

  /** datePicker, "End Date" */
  get endDate(): ApexItem {
    return new ApexItem(this.page, 'P12_END_DATE', 12);
  }

  /** textField, "Reason" */
  get reason(): ApexItem {
    return new ApexItem(this.page, 'P12_REASON', 12);
  }

  /** "Cancel" */
  async clickCancel(): Promise<void> {
    await clickButton(this.page, 'Cancel', { pageId: 12, identifier: 'cancel' });
  }

  /** "Save Blockout" */
  async clickSaveBlockout(): Promise<void> {
    await clickButton(this.page, 'Save Blockout', { pageId: 12, identifier: 'save-blockout' });
  }
}
