/**
 * GENERATED by apx-testgen from pages/p00010-musician-portal.apx — DO NOT EDIT.
 * Typed accessor page object built on @apx/testkit primitives — no raw
 * selectors. Item accessors rest on the VERIFIED apex.item contract; button
 * methods use accessible-role/label locators (region/button DOM convention
 * still open — see docs/grammar-assumptions.md). Click methods pass their
 * button's semantic identity (pageId + .apx identifier) through to
 * clickButton() so coverage tracking never collapses two different,
 * same-labeled buttons into one entry -- see @apx/testkit's coverage.ts.
 * Buttons whose label collides with another button's on this same page do
 * NOT get a generated click method at all -- see the comment in their
 * place below for why and what would resolve it.
 */
import type { Page } from '@playwright/test';
import { ApexItem, apexPageUrl, assessNavigationSafety, clickButton, gotoApexPageAuto } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

export class MusicianPortalPage {
  static readonly alias = 'musician-portal';

  constructor(private readonly page: Page) {}

  url(): string {
    return apexPageUrl(APP_BASE, MusicianPortalPage.alias, true);
  }

  /** Navigate only when the page's declared security/mode permits a direct URL. */
  async goto(): Promise<string[]> {
    return gotoApexPageAuto(
      this.page,
      this.url(),
      assessNavigationSafety({ pageAccessProtection: 'argumentsMustHaveChecksum', isPublic: false }),
    );
  }

  /** hidden */
  get action(): ApexItem {
    return new ApexItem(this.page, 'P10_ACTION', 10);
  }

  /** hidden */
  get rosterId(): ApexItem {
    return new ApexItem(this.page, 'P10_ROSTER_ID', 10);
  }

  /** hidden */
  get rowVersion(): ApexItem {
    return new ApexItem(this.page, 'P10_ROW_VERSION', 10);
  }

  /** "Schedule Blockout" */
  async clickScheduleBlockout(): Promise<void> {
    await clickButton(this.page, 'Schedule Blockout', { pageId: 10, identifier: 'schedule-blockout' });
  }
}
