/**
 * GENERATED by apx-testgen from pages/p09999-login.apx — DO NOT EDIT.
 * Typed accessor page object built on @apx/testkit primitives — no raw
 * selectors. Item accessors rest on the VERIFIED apex.item contract; button
 * methods use accessible-role/label locators (region/button DOM convention
 * still open — see docs/grammar-assumptions.md). Click methods pass their
 * button's semantic identity (pageId + .apx identifier) through to
 * clickButton() so coverage tracking never collapses two different,
 * same-labeled buttons into one entry -- see @apx/testkit's coverage.ts.
 * Buttons whose label collides with another button's on this same page do
 * NOT get a generated click method at all -- see the comment in their
 * place below for why and what would resolve it.
 */
import type { Page } from '@playwright/test';
import { ApexItem, apexPageUrl, assessNavigationSafety, clickButton, gotoApexPageAuto } from '@apx/testkit';
import { APP_BASE } from '../playwright.config.js';

export class LoginPage {
  static readonly alias = 'login';

  constructor(private readonly page: Page) {}

  url(): string {
    return apexPageUrl(APP_BASE, LoginPage.alias, true);
  }

  /** Navigate only when the page's declared security/mode permits a direct URL. */
  async goto(): Promise<string[]> {
    return gotoApexPageAuto(
      this.page,
      this.url(),
      assessNavigationSafety({ pageAccessProtection: 'argumentsMustHaveChecksum', isPublic: true }),
    );
  }

  /** password, "Password" */
  get password(): ApexItem {
    return new ApexItem(this.page, 'P9999_PASSWORD', 9999);
  }

  /** checkbox, "Remember username" */
  get remember(): ApexItem {
    return new ApexItem(this.page, 'P9999_REMEMBER', 9999);
  }

  /** textField, "Username" */
  get username(): ApexItem {
    return new ApexItem(this.page, 'P9999_USERNAME', 9999);
  }

  /** "Sign In" */
  async clickLogin(): Promise<void> {
    await clickButton(this.page, 'Sign In', { pageId: 9999, identifier: 'login' });
  }
}
