-- ============================================================================
-- WorshipFlow: Sprint 0 - Database Foundation & Baseline Data
-- Script: 01_tables_and_indexes.sql
-- Description: Creates all 12 core tables, constraints, indexes, and views.
-- Target: Oracle Database 23ai / 19c+ (Prefix: WS_)
-- ============================================================================

-- Drop objects if existing (clean idempotent replay)
BEGIN
    FOR r IN (SELECT object_name, object_type 
                FROM user_objects 
               WHERE object_name LIKE 'WS_%' 
                 AND object_type IN ('VIEW', 'TABLE')) LOOP
        BEGIN
            IF r.object_type = 'VIEW' THEN
                EXECUTE IMMEDIATE 'DROP VIEW ' || r.object_name;
            ELSIF r.object_type = 'TABLE' THEN
                EXECUTE IMMEDIATE 'DROP TABLE ' || r.object_name || ' CASCADE CONSTRAINTS PURGE';
            END IF;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

-- ----------------------------------------------------------------------------
-- 1. WS_MEMBERS
-- ----------------------------------------------------------------------------
CREATE TABLE ws_members (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_members PRIMARY KEY,
    username           VARCHAR2(100) NOT NULL CONSTRAINT uq_ws_members_username UNIQUE,
    full_name          VARCHAR2(150) NOT NULL,
    email              VARCHAR2(255) NOT NULL CONSTRAINT uq_ws_members_email UNIQUE,
    phone              VARCHAR2(50),
    member_role        VARCHAR2(30) DEFAULT 'MUSICIAN' NOT NULL CONSTRAINT ck_ws_members_role CHECK (member_role IN ('LEADER', 'MUSICIAN', 'ADMIN', 'TECH')),
    max_services_month NUMBER DEFAULT 4 NOT NULL,
    is_active          VARCHAR2(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_ws_members_active CHECK (is_active IN ('Y', 'N')),
    created_at         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL,
    created_by         VARCHAR2(100),
    updated_at         TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by         VARCHAR2(100)
);

-- ----------------------------------------------------------------------------
-- 2. WS_INSTRUMENTS
-- ----------------------------------------------------------------------------
CREATE TABLE ws_instruments (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_instruments PRIMARY KEY,
    name          VARCHAR2(100) NOT NULL CONSTRAINT uq_ws_instruments_name UNIQUE,
    code          VARCHAR2(30) NOT NULL CONSTRAINT uq_ws_instruments_code UNIQUE,
    category      VARCHAR2(30) DEFAULT 'BAND' NOT NULL CONSTRAINT ck_ws_instruments_cat CHECK (category IN ('RHYTHM', 'MELODY', 'VOCALS', 'PRODUCTION')),
    display_order NUMBER DEFAULT 0 NOT NULL,
    is_active     VARCHAR2(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_ws_instruments_active CHECK (is_active IN ('Y', 'N'))
);

-- ----------------------------------------------------------------------------
-- 3. WS_MEMBER_INSTRUMENTS
-- ----------------------------------------------------------------------------
CREATE TABLE ws_member_instruments (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_member_instruments PRIMARY KEY,
    member_id     NUMBER NOT NULL CONSTRAINT fk_ws_mi_member REFERENCES ws_members(id) ON DELETE CASCADE,
    instrument_id NUMBER NOT NULL CONSTRAINT fk_ws_mi_instrument REFERENCES ws_instruments(id) ON DELETE CASCADE,
    is_primary    VARCHAR2(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_ws_mi_primary CHECK (is_primary IN ('Y', 'N')),
    skill_level   VARCHAR2(20) DEFAULT 'INTERMEDIATE' NOT NULL CONSTRAINT ck_ws_mi_skill CHECK (skill_level IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
    CONSTRAINT uq_ws_member_instruments UNIQUE (member_id, instrument_id)
);

-- ----------------------------------------------------------------------------
-- 4. WS_SERVICE_TEMPLATES
-- ----------------------------------------------------------------------------
CREATE TABLE ws_service_templates (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_service_templates PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL CONSTRAINT uq_ws_service_templates_name UNIQUE,
    description VARCHAR2(500),
    is_active   VARCHAR2(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_ws_service_templates_active CHECK (is_active IN ('Y', 'N')),
    created_at  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL
);

-- ----------------------------------------------------------------------------
-- 5. WS_SERVICE_TEMPLATE_SLOTS
-- ----------------------------------------------------------------------------
CREATE TABLE ws_service_template_slots (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_service_template_slots PRIMARY KEY,
    template_id   NUMBER NOT NULL CONSTRAINT fk_ws_sts_template REFERENCES ws_service_templates(id) ON DELETE CASCADE,
    instrument_id NUMBER NOT NULL CONSTRAINT fk_ws_sts_instrument REFERENCES ws_instruments(id) ON DELETE CASCADE,
    slot_number   NUMBER DEFAULT 1 NOT NULL,
    is_mandatory  VARCHAR2(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_ws_sts_mandatory CHECK (is_mandatory IN ('Y', 'N')),
    CONSTRAINT uq_ws_sts_slot UNIQUE (template_id, instrument_id, slot_number)
);

-- ----------------------------------------------------------------------------
-- 6. WS_BANDS
-- ----------------------------------------------------------------------------
CREATE TABLE ws_bands (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_bands PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL CONSTRAINT uq_ws_bands_name UNIQUE,
    leader_id   NUMBER CONSTRAINT fk_ws_bands_leader REFERENCES ws_members(id) ON DELETE SET NULL,
    description VARCHAR2(500),
    is_active   VARCHAR2(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_ws_bands_active CHECK (is_active IN ('Y', 'N')),
    created_at  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL
);

-- ----------------------------------------------------------------------------
-- 7. WS_BAND_MEMBERS
-- ----------------------------------------------------------------------------
CREATE TABLE ws_band_members (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_band_members PRIMARY KEY,
    band_id       NUMBER NOT NULL CONSTRAINT fk_ws_bm_band REFERENCES ws_bands(id) ON DELETE CASCADE,
    member_id     NUMBER NOT NULL CONSTRAINT fk_ws_bm_member REFERENCES ws_members(id) ON DELETE CASCADE,
    instrument_id NUMBER NOT NULL CONSTRAINT fk_ws_bm_instrument REFERENCES ws_instruments(id) ON DELETE CASCADE,
    CONSTRAINT uq_ws_band_members UNIQUE (band_id, member_id, instrument_id)
);

-- ----------------------------------------------------------------------------
-- 8. WS_MEMBER_BLOCKOUTS
-- ----------------------------------------------------------------------------
CREATE TABLE ws_member_blockouts (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_member_blockouts PRIMARY KEY,
    member_id  NUMBER NOT NULL CONSTRAINT fk_ws_blockouts_member REFERENCES ws_members(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date   DATE NOT NULL,
    reason     VARCHAR2(255),
    created_at TIMESTAMP WITH LOCAL TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL,
    CONSTRAINT ck_ws_blockout_dates CHECK (start_date <= end_date)
);

-- ----------------------------------------------------------------------------
-- 9. WS_SERVICES
-- ----------------------------------------------------------------------------
CREATE TABLE ws_services (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_services PRIMARY KEY,
    template_id        NUMBER CONSTRAINT fk_ws_services_template REFERENCES ws_service_templates(id) ON DELETE SET NULL,
    name               VARCHAR2(150) NOT NULL,
    service_date       DATE NOT NULL,
    start_time         VARCHAR2(10) DEFAULT '10:00',
    status             VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL CONSTRAINT ck_ws_services_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'COMPLETED', 'CANCELLED')),
    band_id            NUMBER CONSTRAINT fk_ws_services_band REFERENCES ws_bands(id) ON DELETE SET NULL,
    notes              VARCHAR2(1000),
    row_version_number NUMBER DEFAULT 1 NOT NULL,
    created_at         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL,
    created_by         VARCHAR2(100),
    updated_at         TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by         VARCHAR2(100)
);

-- ----------------------------------------------------------------------------
-- 10. WS_SERVICE_ROSTER
-- ----------------------------------------------------------------------------
CREATE TABLE ws_service_roster (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_service_roster PRIMARY KEY,
    service_id         NUMBER NOT NULL CONSTRAINT fk_ws_roster_service REFERENCES ws_services(id) ON DELETE CASCADE,
    instrument_id      NUMBER NOT NULL CONSTRAINT fk_ws_roster_instrument REFERENCES ws_instruments(id),
    slot_number        NUMBER DEFAULT 1 NOT NULL,
    member_id          NUMBER CONSTRAINT fk_ws_roster_member REFERENCES ws_members(id) ON DELETE SET NULL,
    replaced_member_id NUMBER CONSTRAINT fk_ws_roster_replaced REFERENCES ws_members(id) ON DELETE SET NULL,
    status             VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CONSTRAINT ck_ws_roster_status CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED')),
    decline_reason     VARCHAR2(255),
    confirmed_at       TIMESTAMP WITH LOCAL TIME ZONE,
    row_version_number NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT uq_ws_service_roster UNIQUE (service_id, instrument_id, slot_number)
);

-- ----------------------------------------------------------------------------
-- 11. WS_SONGS
-- ----------------------------------------------------------------------------
CREATE TABLE ws_songs (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_songs PRIMARY KEY,
    title       VARCHAR2(200) NOT NULL,
    artist      VARCHAR2(150),
    default_key VARCHAR2(10) NOT NULL CONSTRAINT ck_ws_songs_key CHECK (
        default_key IN (
            'C', 'C#', 'Db', 'D', 'D#', 'Eb', 'E', 'F', 'F#', 'Gb', 'G', 'G#', 'Ab', 'A', 'A#', 'Bb', 'B',
            'Cm', 'C#m', 'Dbm', 'Dm', 'D#m', 'Ebm', 'Em', 'Fm', 'F#m', 'Gbm', 'Gm', 'G#m', 'Abm', 'Am', 'A#m', 'Bbm', 'Bm'
        )
    ),
    youtube_url VARCHAR2(1000),
    bpm         NUMBER,
    is_active   VARCHAR2(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_ws_songs_active CHECK (is_active IN ('Y', 'N')),
    created_at  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL
);

-- ----------------------------------------------------------------------------
-- 12. WS_SERVICE_SETLIST
-- ----------------------------------------------------------------------------
CREATE TABLE ws_service_setlist (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_ws_service_setlist PRIMARY KEY,
    service_id  NUMBER NOT NULL CONSTRAINT fk_ws_setlist_service REFERENCES ws_services(id) ON DELETE CASCADE,
    song_id     NUMBER NOT NULL CONSTRAINT fk_ws_setlist_song REFERENCES ws_songs(id) ON DELETE CASCADE,
    play_order  NUMBER NOT NULL,
    service_key VARCHAR2(10) NOT NULL CONSTRAINT ck_ws_setlist_key CHECK (
        service_key IN (
            'C', 'C#', 'Db', 'D', 'D#', 'Eb', 'E', 'F', 'F#', 'Gb', 'G', 'G#', 'Ab', 'A', 'A#', 'Bb', 'B',
            'Cm', 'C#m', 'Dbm', 'Dm', 'D#m', 'Ebm', 'Em', 'Fm', 'F#m', 'Gbm', 'Gm', 'G#m', 'Abm', 'Am', 'A#m', 'Bbm', 'Bm'
        )
    ),
    notes       VARCHAR2(500),
    CONSTRAINT uq_ws_service_setlist UNIQUE (service_id, play_order)
);

-- ----------------------------------------------------------------------------
-- Performance Indexes
-- ----------------------------------------------------------------------------
CREATE INDEX idx_ws_mi_member       ON ws_member_instruments (member_id);
CREATE INDEX idx_ws_mi_instrument   ON ws_member_instruments (instrument_id);
CREATE INDEX idx_ws_sts_template    ON ws_service_template_slots (template_id);
CREATE INDEX idx_ws_bm_band         ON ws_band_members (band_id);
CREATE INDEX idx_ws_bm_member       ON ws_band_members (member_id);
CREATE INDEX idx_ws_blockout_lookup ON ws_member_blockouts (member_id, start_date, end_date);
CREATE INDEX idx_ws_services_date   ON ws_services (service_date, status);
CREATE INDEX idx_ws_roster_member   ON ws_service_roster (member_id, status);
CREATE INDEX idx_ws_roster_service  ON ws_service_roster (service_id);
CREATE INDEX idx_ws_songs_title     ON ws_songs (UPPER(title));
-- Note: ws_service_setlist (service_id, play_order) is automatically indexed by uq_ws_service_setlist constraint

-- ----------------------------------------------------------------------------
-- Retroactive Conflict Detection View
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW ws_v_roster_conflicts AS
SELECT 
    sr.id            AS roster_id,
    sr.service_id,
    s.name           AS service_name,
    s.service_date,
    m.id             AS member_id,
    m.full_name      AS member_name,
    i.name           AS instrument_name,
    sr.status        AS roster_status,
    mb.start_date    AS blockout_start,
    mb.end_date      AS blockout_end,
    mb.reason        AS blockout_reason
FROM ws_service_roster sr
JOIN ws_services s         ON s.id = sr.service_id
JOIN ws_members m          ON m.id = sr.member_id
JOIN ws_instruments i      ON i.id = sr.instrument_id
JOIN ws_member_blockouts mb ON mb.member_id = m.id
WHERE s.service_date BETWEEN mb.start_date AND mb.end_date
  AND sr.status IN ('PENDING', 'ACCEPTED')
  AND s.status IN ('DRAFT', 'PUBLISHED');
